# STR1="SAMBHAV"
# len1= len(STR1)
# STR2="SHUKLA"
# len2= len(STR2)
# print(STR1 + STR2)
# print(len1 + len2)

# print(STR1[0])


# # COMTANINATION
# STRING1="`Hello"
# STRING2=" World`" 
# FINAL_STRING= STRING1 + STRING2
# print(FINAL_STRING)
# len1=len(STRING1)
# len2=len(STRING2)
# TOTAL_LENGTH=len1 + len2
# print(TOTAL_LENGTH)     


# # INDEXING
number_1="god morning"
print(str(number_1[9]))
# slicing
print(str(number_1[0:3]))
print(str(number_1[4:11]))
